server:
  port: 8380
  

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
spring:
  application:
    name: shoppingcart
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/shopping
  datasource:
    max-wait: 10000
    max-active: 30
    